name: Feature Request
description: Request a new feature
title: "[Feature Request] "
projects: "agilesix/simpler-grants-sandbox"
type: Enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem_statement
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    id: desired_behavior
    attributes:
      label: A clear and concise description of what you want to happen
      description: Help us understand your improvement ideas.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/HHS/simpler-grants-gov/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
