name: Internal - Epic
description: Describe a large body of work that can be broken down into smaller tasks
projects: "agilesix/simpler-grants-sandbox"
type: Epic
body:      
  - type: textarea
    id: summary
    attributes: 
      label: Technical description
      description: A clear summmary of the body of work
    validations:
      required: true
      
  - type: textarea
    id: key_risks
    attributes: 
      label: Key risks
      description: The key risks for the body of work
    validations:
      required: true



  
