name: Internal - Task
description: Describe a task that needs to be completed
projects: "agilesix/simpler-grants-sandbox"
type: Task
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of the task
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: A clear and concise checklist of expectations including definition of done
      placeholder: Explain the steps to success!
    validations:
      required: false



      
