name: Lint - Sprint rollover

on:
  workflow_dispatch: # for manual runs

jobs:
  sprint-rollover:
    name: Roll over open tickets
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: agilesix
          number: 18
          token: ${{ secrets.GH_PROJECT_ACCESS_TOKEN }}
          iteration-field: Sprint
          iteration: last
          new-iteration: current
          excluded-statuses: "Done"
