name: "Populate FeatureBase board"

on:
  pull_request:
    paths:
      - "linters/load_pb_board/**"
      - ".github/workflows/populate-feature-base-board.yml"
  workflow_dispatch: # for manual runs

permissions:
  issues: read

defaults:
  run:
    working-directory: ./linters/load_pb_board

jobs:
  populate:
    runs-on: ubuntu-latest

    env:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIDER_API_TOKEN: ${{ secrets.FIDER_TOKEN }}
      FEATURE_BASE_API_TOKEN: ${{ secrets.FEATURE_BASE_TOKEN }}
      FEATURE_BASE_GITHUB_FIELD_ID: "685ac338d7b32b47dce5ef03"
      FIDER_BOARD: "simplergrants"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run script (dry run)
        if: github.event_name == 'pull_request'
        run: |
          python run.py \
            --org "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --label proposal \
            --platform featurebase \
            --dry-run

      - name: Run script (real run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          python run.py \
            --org "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --label proposal \
            --platform featurebase
