name: "Populate Fider board"

on:
  pull_request:
    paths:
      - "linters/load_fider_board/**"
      - ".github/workflows/run-populate-fider-board.yml"
  workflow_dispatch: # for manual runs

permissions:
  issues: read

jobs:
  populate:
    runs-on: ubuntu-latest

    env:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIDER_API_TOKEN: ${{ secrets.FIDER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run script (dry run)
        if: github.event_name == 'pull_request'
        run: |
          python ./linters/load_fider_board/run.py \
            --org "${{ github.event.repository.owner.name }}" \
            --repo "${{ github.event.repository.name }}" \
            --label proposal \
            --board simplergrants \
            --dry-run

      - name: Run script (real run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          python ./linters/load_fider_board/run.py \
            --org "${{ github.event.repository.owner.name }}" \
            --repo "${{ github.event.repository.name }}" \
            --label proposal \
            --board simplergrants
